# Generated by Django 6.0.5 on 2026-05-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneimage',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='PhoneImage',
        ),
    ]
